disabled_rules:
  - trailing_whitespace
  - shorthand_operator
  - large_tuple
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - Submodules
file_length:
  warning: 200
  error: 300
variable_name:
  min_length: 2
line_length:
  warning: 120
  error: 130
